### ISSUE TITLE
can't trigger click event

### ISSUE THREAD

**Issue by LudoFont** [jwerts/angular2-esri-play#2]
Hi Josh,

I'm currently trying to trigger click events on a layer with graphics I created and added to the map.
There is no way to trigger these events, and I can't figure out why.
The code I put in the app.component.ts :

  ```
  onViewCreated() {
        console.log('view created');

        var points = [
            {x: 166.454, y:-22.306},
            {x: 166.442, y:-22.291},
            {x: 166.457, y:-22.29},
            {x: 166.4356, y:-22.3026}
        ];

        var layer = new GraphicsLayer();

        points.forEach(point => {
            let g = new Graphic({
                geometry: new Point({
                    x: point.x,
                    y: point.y,
                    spatialReference: 4326
                }),
                attributes: {
                    index: 0
                },
                symbol: new PictureMarkerSymbol({
                    url: 'http://www.myiconfinder.com/uploads/iconsets/256-256-a5485b563efc4511e0cd8bd04ad0fe9e.png',
                    width: 20,
                    height: 20,
                    yoffset: 10
                })
            });

            layer.add(g);
        });

        layer.on("click", function(){
            console.log("click");
        })

        this.mapService.map.add(layer);
    }

```
Could you tell me what is wrong with this approach ?

A similar working JS example (log is ok in console) : http://jsfiddle.net/uphyh41h/

Thank you,

Ludovic

**Comment by jwerts** [comment]
@LudoFont In the 4.x API, you can't add a click handler to graphics or to a GraphicsLayer.  You have to go through the view itself:  https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#event:click

It's a little convoluted compared to the 3.x way.
